"""
Column canonicalisation — behavioural equivalence with the pandas version.

normalize_columns was a pandas DataFrame transform. pandas cost ~56 MB of the
512 MB Render instance (and pulled numpy, ~another 30) to do a column remap,
so it was rewritten against plain dicts.

Every expectation below was CAPTURED FROM THE PANDAS IMPLEMENTATION before the
rewrite, so this file is the proof that behaviour did not change. Do not edit
an expectation to make a test pass — it would be asserting the new code against
itself rather than against what shipped.

Run: python3 backend/test_column_normalisation.py
"""
import json
import os
import sys

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))

import logging
logging.disable(logging.CRITICAL)

import api_server as A

fails: list[str] = []


def ok(cond, msg):
    print(("PASS  " if cond else "FAIL  ") + msg)
    if not cond:
        fails.append(msg)


# (input records, expected records, expected detected cols, expected mapped cols)
CASES = {'plain': {'input': [{'Full Name': 'Jane Okonjo',
                      'Designation': 'CFO',
                      'Company': 'Acme',
                      'Location': 'London'},
                     {'Full Name': 'Raj Patel',
                      'Designation': 'CTO',
                      'Company': 'Acme',
                      'Location': 'Delhi'}],
           'records': [{'Company': 'Acme',
                        'Designation': 'CFO',
                        'FirstName': 'Jane',
                        'FullName': 'Jane Okonjo',
                        'LastName': 'Okonjo',
                        'Location': 'London'},
                       {'Company': 'Acme',
                        'Designation': 'CTO',
                        'FirstName': 'Raj',
                        'FullName': 'Raj Patel',
                        'LastName': 'Patel',
                        'Location': 'Delhi'}],
           'detected': ['Full Name', 'Designation', 'Company', 'Location'],
           'mapped': ['FullName',
                      'Designation',
                      'Company',
                      'Location',
                      'FirstName',
                      'LastName']},
 'alias_headers': {'input': [{'first name': 'Jane',
                              'last name': 'Okonjo',
                              'job title': 'CFO',
                              'organization': 'Acme'},
                             {'first name': 'Raj',
                              'last name': 'Patel',
                              'job title': 'CTO',
                              'organization': 'Acme'}],
                   'records': [{'Company': 'Acme',
                                'Designation': 'CFO',
                                'FirstName': 'Jane',
                                'LastName': 'Okonjo'},
                               {'Company': 'Acme',
                                'Designation': 'CTO',
                                'FirstName': 'Raj',
                                'LastName': 'Patel'}],
                   'detected': ['first name', 'last name', 'job title', 'organization'],
                   'mapped': ['FirstName', 'LastName', 'Designation', 'Company']},
 'fullname_split': {'input': [{'FullName': 'Jane Mary Okonjo', 'Designation': 'CFO'},
                              {'FullName': 'Cher', 'Designation': 'Artist'},
                              {'FullName': '  Raj  Patel ', 'Designation': 'CTO'}],
                    'records': [{'Designation': 'CFO',
                                 'FirstName': 'Jane',
                                 'FullName': 'Jane Mary Okonjo',
                                 'LastName': 'Mary Okonjo'},
                                {'Designation': 'Artist',
                                 'FirstName': 'Cher',
                                 'FullName': 'Cher',
                                 'LastName': ''},
                                {'Designation': 'CTO',
                                 'FirstName': 'Raj',
                                 'FullName': '  Raj  Patel ',
                                 'LastName': 'Patel'}],
                    'detected': ['FullName', 'Designation'],
                    'mapped': ['FullName', 'Designation', 'FirstName', 'LastName']},
 'contact_name_fallback': {'input': [{'contact name': 'Jane Okonjo', 'Designation': 'CFO'},
                                     {'contact name': 'Raj Patel', 'Designation': 'CTO'}],
                           'records': [{'Designation': 'CFO',
                                        'FirstName': 'Jane',
                                        'FullName': 'Jane Okonjo',
                                        'LastName': 'Okonjo'},
                                       {'Designation': 'CTO',
                                        'FirstName': 'Raj',
                                        'FullName': 'Raj Patel',
                                        'LastName': 'Patel'}],
                           'detected': ['contact name', 'Designation'],
                           'mapped': ['FullName', 'Designation', 'FirstName', 'LastName']},
 'headline_fallback': {'input': [{'FullName': 'Jane Okonjo',
                                  'Designation': '',
                                  'linkedin_headline': 'Service Engineer at Recorders & '
                                                       'Medicare Systems'},
                                 {'FullName': 'Raj Patel',
                                  'Designation': 'CTO',
                                  'linkedin_headline': 'CTO at Acme'},
                                 {'FullName': 'Li Wei',
                                  'linkedin_headline': 'Head of Data at Foo Corp'}],
                       'records': [{'Designation': 'Service Engineer',
                                    'FirstName': 'Jane',
                                    'FullName': 'Jane Okonjo',
                                    'LastName': 'Okonjo',
                                    'linkedin_headline': 'Service Engineer'},
                                   {'Designation': 'CTO',
                                    'FirstName': 'Raj',
                                    'FullName': 'Raj Patel',
                                    'LastName': 'Patel',
                                    'linkedin_headline': 'CTO'},
                                   {'Designation': 'Head of Data',
                                    'FirstName': 'Li',
                                    'FullName': 'Li Wei',
                                    'LastName': 'Wei',
                                    'linkedin_headline': 'Head of Data'}],
                       'detected': ['FullName', 'Designation', 'linkedin_headline'],
                       'mapped': ['FullName',
                                  'Designation',
                                  'linkedin_headline',
                                  'FirstName',
                                  'LastName']},
 'headline_only': {'input': [{'FullName': 'Jane Okonjo',
                              'linkedin_headline': 'Analyst at Beta Ltd'}],
                   'records': [{'Designation': 'Analyst',
                                'FirstName': 'Jane',
                                'FullName': 'Jane Okonjo',
                                'LastName': 'Okonjo',
                                'linkedin_headline': 'Analyst'}],
                   'detected': ['FullName', 'linkedin_headline'],
                   'mapped': ['FullName',
                              'linkedin_headline',
                              'FirstName',
                              'LastName',
                              'Designation']},
 'company_from_linkedin_slug': {'input': [{'FullName': 'Jane Okonjo',
                                           'Designation': 'CFO',
                                           'job_org_linkedin_url': 'https://linkedin.com/company/acme-holdings-plc/'},
                                          {'FullName': 'Raj Patel',
                                           'Designation': 'CTO',
                                           'job_org_linkedin_url': 'https://linkedin.com/company/acme-holdings-plc'}],
                                'records': [{'Company': 'Acme Holdings Plc',
                                             'Designation': 'CFO',
                                             'FirstName': 'Jane',
                                             'FullName': 'Jane Okonjo',
                                             'LastName': 'Okonjo',
                                             'job_org_linkedin_url': 'https://linkedin.com/company/acme-holdings-plc/'},
                                            {'Company': 'Acme Holdings Plc',
                                             'Designation': 'CTO',
                                             'FirstName': 'Raj',
                                             'FullName': 'Raj Patel',
                                             'LastName': 'Patel',
                                             'job_org_linkedin_url': 'https://linkedin.com/company/acme-holdings-plc'}],
                                'detected': ['FullName', 'Designation', 'job_org_linkedin_url'],
                                'mapped': ['FullName',
                                           'Designation',
                                           'job_org_linkedin_url',
                                           'FirstName',
                                           'LastName',
                                           'Company']},
 'company_from_email_domain': {'input': [{'FullName': 'Jane Okonjo',
                                          'Designation': 'CFO',
                                          'Company': '',
                                          'email_domain': 'acme.com'},
                                         {'FullName': 'Raj Patel',
                                          'Designation': 'CTO',
                                          'Company': 'Beta',
                                          'email_domain': 'beta.com'}],
                               'records': [{'Company': 'Acme',
                                            'Designation': 'CFO',
                                            'FirstName': 'Jane',
                                            'FullName': 'Jane Okonjo',
                                            'LastName': 'Okonjo',
                                            'email_domain': 'acme.com'},
                                           {'Company': 'Beta',
                                            'Designation': 'CTO',
                                            'FirstName': 'Raj',
                                            'FullName': 'Raj Patel',
                                            'LastName': 'Patel',
                                            'email_domain': 'beta.com'}],
                               'detected': ['FullName',
                                            'Designation',
                                            'Company',
                                            'email_domain'],
                               'mapped': ['FullName',
                                          'Designation',
                                          'Company',
                                          'email_domain',
                                          'FirstName',
                                          'LastName']},
 'location_coalesce': {'input': [{'FullName': 'Jane Okonjo',
                                  'job_city': 'London',
                                  'job_country': 'UK'},
                                 {'FullName': 'Raj Patel',
                                  'job_city': '',
                                  'job_country': 'India'},
                                 {'FullName': 'Li Wei', 'job_city': None, 'job_country': None}],
                       'records': [{'FirstName': 'Jane',
                                    'FullName': 'Jane Okonjo',
                                    'LastName': 'Okonjo',
                                    'Location': 'London',
                                    'job_city': 'London',
                                    'job_country': 'UK'},
                                   {'FirstName': 'Raj',
                                    'FullName': 'Raj Patel',
                                    'LastName': 'Patel',
                                    'Location': 'India',
                                    'job_city': '',
                                    'job_country': 'India'},
                                   {'FirstName': 'Li',
                                    'FullName': 'Li Wei',
                                    'LastName': 'Wei',
                                    'Location': '',
                                    'job_city': '',
                                    'job_country': ''}],
                       'detected': ['FullName', 'job_city', 'job_country'],
                       'mapped': ['FullName',
                                  'job_city',
                                  'job_country',
                                  'FirstName',
                                  'LastName',
                                  'Location']},
 'industry_fallback': {'input': [{'FullName': 'Jane Okonjo',
                                  'Industry_Hint': '',
                                  'linkedin_industry': 'Banking'},
                                 {'FullName': 'Raj Patel',
                                  'Industry_Hint': 'Software',
                                  'linkedin_industry': 'IT'}],
                       'records': [{'FirstName': 'Jane',
                                    'FullName': 'Jane Okonjo',
                                    'Industry_Hint': 'Banking',
                                    'LastName': 'Okonjo',
                                    'linkedin_industry': 'Banking'},
                                   {'FirstName': 'Raj',
                                    'FullName': 'Raj Patel',
                                    'Industry_Hint': 'Software',
                                    'LastName': 'Patel',
                                    'linkedin_industry': 'IT'}],
                       'detected': ['FullName', 'Industry_Hint', 'linkedin_industry'],
                       'mapped': ['FullName',
                                  'Industry_Hint',
                                  'linkedin_industry',
                                  'FirstName',
                                  'LastName']},
 'missing_keys_across_rows': {'input': [{'FullName': 'Jane Okonjo',
                                         'Designation': 'CFO',
                                         'Company': 'Acme'},
                                        {'FullName': 'Raj Patel'},
                                        {'Designation': 'CTO', 'Location': 'Delhi'}],
                              'records': [{'Company': 'Acme',
                                           'Designation': 'CFO',
                                           'FirstName': 'Jane',
                                           'FullName': 'Jane Okonjo',
                                           'LastName': 'Okonjo',
                                           'Location': ''},
                                          {'Company': '',
                                           'Designation': '',
                                           'FirstName': 'Raj',
                                           'FullName': 'Raj Patel',
                                           'LastName': 'Patel',
                                           'Location': ''},
                                          {'Company': '',
                                           'Designation': 'CTO',
                                           'FirstName': '',
                                           'FullName': '',
                                           'LastName': '',
                                           'Location': 'Delhi'}],
                              'detected': ['FullName', 'Designation', 'Company'],
                              'mapped': ['FullName',
                                         'Designation',
                                         'Company',
                                         'Location',
                                         'FirstName',
                                         'LastName']},
 'duplicate_aliases': {'input': [{'first name': 'Jane',
                                  'firstname': 'IGNORED',
                                  'last name': 'Okonjo',
                                  'Designation': 'CFO'}],
                       'records': [{'Designation': 'CFO',
                                    'FirstName': 'Jane',
                                    'LastName': 'Okonjo',
                                    'firstname': 'IGNORED'}],
                       'detected': ['first name', 'firstname', 'last name', 'Designation'],
                       'mapped': ['FirstName', 'firstname', 'LastName', 'Designation']},
 'messy_header_punctuation': {'input': [{'First Name!': 'Jane',
                                         'Last-Name': 'Okonjo',
                                         'Job Title:': 'CFO'}],
                              'records': [{'Designation': 'CFO',
                                           'FirstName': 'Jane',
                                           'LastName': 'Okonjo'}],
                              'detected': ['First Name!', 'Last-Name', 'Job Title:'],
                              'mapped': ['FirstName', 'LastName', 'Designation']},
 'nulls_and_blanks': {'input': [{'FullName': 'Jane Okonjo',
                                 'Designation': None,
                                 'Company': None,
                                 'Location': ''},
                                {'FullName': '',
                                 'Designation': 'CTO',
                                 'Company': 'Acme',
                                 'Location': 'Delhi'}],
                      'records': [{'Company': '',
                                   'Designation': '',
                                   'FirstName': 'Jane',
                                   'FullName': 'Jane Okonjo',
                                   'LastName': 'Okonjo',
                                   'Location': ''},
                                  {'Company': 'Acme',
                                   'Designation': 'CTO',
                                   'FirstName': '',
                                   'FullName': '',
                                   'LastName': '',
                                   'Location': 'Delhi'}],
                      'detected': ['FullName', 'Designation', 'Company', 'Location'],
                      'mapped': ['FullName',
                                 'Designation',
                                 'Company',
                                 'Location',
                                 'FirstName',
                                 'LastName']},
 'numeric_values': {'input': [{'FullName': 'Jane Okonjo',
                               'Designation': 'CFO',
                               'Company': 'Acme',
                               'employee_id': 12345},
                              {'FullName': 'Raj Patel',
                               'Designation': 'CTO',
                               'Company': 'Acme',
                               'employee_id': 99}],
                    'records': [{'Company': 'Acme',
                                 'Designation': 'CFO',
                                 'FirstName': 'Jane',
                                 'FullName': 'Jane Okonjo',
                                 'LastName': 'Okonjo',
                                 'employee_id': 12345},
                                {'Company': 'Acme',
                                 'Designation': 'CTO',
                                 'FirstName': 'Raj',
                                 'FullName': 'Raj Patel',
                                 'LastName': 'Patel',
                                 'employee_id': 99}],
                    'detected': ['FullName', 'Designation', 'Company', 'employee_id'],
                    'mapped': ['FullName',
                               'Designation',
                               'Company',
                               'employee_id',
                               'FirstName',
                               'LastName']}}

for name, case in CASES.items():
    records, detected, mapped = A.canonicalise_records([dict(r) for r in case["input"]])
    ok(detected == case["detected"], f"{name}: detected columns")
    ok(mapped == case["mapped"], f"{name}: mapped columns")
    # Compare key sets and values, order-independently.
    same = (len(records) == len(case["records"])
            and all(r == e for r, e in zip(records, case["records"])))
    ok(same, f"{name}: records match the pandas output")
    if not same:
        for i, (r, e) in enumerate(zip(records, case["records"])):
            if r != e:
                diff = {k for k in set(r) | set(e) if r.get(k) != e.get(k)}
                print(f"      row {i}: " + json.dumps(
                    {k: {"got": r.get(k), "want": e.get(k)} for k in diff}, default=str))

# Parser-level checks for the stdlib readers that replaced pd.read_csv /
# pd.read_excel. Both differences from pandas here are deliberate fixes.
recs, det = A._read_csv_bytes(b"Full Name,Designation\nJane,CFO,EXTRA\nRaj,CTO\n")
ok(recs[0]["Full Name"] == "Jane",
   "csv: ragged row keeps column alignment (pandas shifted it into an index)")
recs, det = A._read_csv_bytes(b"Full Name,employee_id\nJane,12345\nRaj,\n")
ok(recs[0]["employee_id"] == "12345",
   "csv: integer id stays '12345' (pandas floated it to 12345.0)")
recs, det = A._read_csv_bytes("\ufeffFull Name,Designation\nJane,CFO\n".encode())
ok(det == ["Full Name", "Designation"], "csv: BOM stripped from the first header")
recs, det = A._read_csv_bytes(b'Full Name,Designation\n"Okonjo, Jane","CFO, Group"\n')
ok(recs[0]["Full Name"] == "Okonjo, Jane", "csv: quoted commas preserved")

print("\n%d failed" % len(fails) if fails else "\nALL PASS")
sys.exit(1 if fails else 0)
